image: metasolutions/node-yarn:latest

options:
  max-time: 8

stepdefinitions:
  - build: &build
      name: Build
      script:
        - node --version
        - yarn --version
        - yarn cache dir
        - export ESJS_VERSION=`jq -r .version package.json` && echo $ESJS_VERSION
        # We allow semantic versioning plus x.y-z (e.g. 4.10-dev which does not exactly conform to semver due to missing patch level)
        - echo $ESJS_VERSION | grep -P -q '^(0|[1-9]\d*)\.(0|[1-9]\d*)(\.*)(0*|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
        - if [ $BITBUCKET_BRANCH == "develop" ] && [[ $ESJS_VERSION != *-dev ]]; then echo "Development version must end with \"-dev\""; exit 1; fi
        # needed with Node 18+ until we have upgraded to Webpack 5:
        # - export NODE_OPTIONS="--openssl-legacy-provider" && echo $NODE_OPTIONS
        - yarn
        - yarn build
        - yarn jsdoc && ls -al out
      artifacts:
        - dist/**
        - out/**
        - node_modules/**
  - test: &test
      name: Test
      script:
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ESIMGVER="develop" ; else ESIMGVER="latest" ; fi
        - echo $ESIMGVER
        - echo "127.0.0.1 entrystore.local" >> /etc/hosts && cat /etc/hosts
        - docker pull metasolutions/entrystore:$ESIMGVER
        - docker run --rm -v $BITBUCKET_CLONE_DIR/tests/entrystore.properties_pipelines:/srv/entrystore/entrystore.properties:ro -p 127.0.0.1:8080:8080 metasolutions/entrystore:$ESIMGVER /srv/entrystore/bin/entrystore --config file:///srv/entrystore/entrystore.properties --port 8080 --log-level info &
        - sleep 15
        - curl -s http://entrystore.local:8080/auth/user
        - cp tests/config.js_pipelines tests/config.js && cat tests/config.js
        - yarn tests
      services:
        - docker
      caches:
        - docker
  - deploy: &deploy
      name: Deploy
      script:
        - export ESJS_VERSION=`jq -r .version package.json` && echo $ESJS_VERSION
        - ( cd dist && rsync -avrz --delete * "deploy@meta1.metasolutions.se:/var/www/entrystore.js/$ESJS_VERSION/" )
        - rsync -avrz --delete out/ "deploy@meta1.metasolutions.se:/var/www/entrystore.js/$ESJS_VERSION/doc/"
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta1.metasolutions.se "cd /var/www/entrystore.js/; rm latest; ln -s $ESJS_VERSION latest" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta1.metasolutions.se "cd /var/www/entrystore.js/; rm stable; ln -s $ESJS_VERSION stable" ; fi

pipelines:
  default:
    - step: *build
    - step: *test
  branches:
    master:
      - step: *build
      - step: *test
      - step: *deploy
    develop:
      - step: *build
      - step: *test
      - step: *deploy
