image: node:4.6.0

pipelines:
  default:
    - step:
        script:
          - npm install
          - npm install -g bower
          - bower install --allow-root
          - ( cd build && ./build.sh )
